const grid=document.getElementById('tourGrid');
const modal=document.getElementById('tourModal');
const modalImage=document.getElementById('modalImage');
const modalBadge=document.getElementById('modalBadge');
const modalTitle=document.getElementById('modalTitle');
const modalPrice=document.getElementById('modalPrice');
const modalSummary=document.getElementById('modalSummary');
const modalMeta=document.getElementById('modalMeta');
const modalRoute=document.getElementById('modalRoute');
const modalIncluded=document.getElementById('modalIncluded');
const modalWhatsapp=document.getElementById('modalWhatsapp');
const filterButtons=[...document.querySelectorAll('[data-filter]')];
const phoneTime=document.getElementById('phoneTime');
const googleReviewsTrack=document.getElementById('googleReviewsTrack');
const googleRating=document.getElementById('googleRating');
const googleRatingStars=document.getElementById('googleRatingStars');
const googleReviewCount=document.getElementById('googleReviewCount');
const googleReviewsStatus=document.getElementById('googleReviewsStatus');
const googleReviewsButton=document.getElementById('googleReviewsButton');
const googleScoreLink=document.getElementById('googleScoreLink');
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
function whatsappLink(t){const message=`Merhaba, ${t.title} (${t.subtitle}) turu hakkında bilgi almak istiyorum. Güncel kontenjan ve rezervasyon bilgisi paylaşabilir misiniz?`;return `https://wa.me/905374978441?text=${encodeURIComponent(message)}`;}
const overnightIds=new Set(['dogu-ekspresi-erzurum-kars-agri-van','buyuk-bati-karadeniz','kadim-topraklar-turu']);
function isOvernight(t){return overnightIds.has(t.id)||t.type==='Konaklamalı'||/Gece/.test(t.duration||'')||/Gece/.test(t.type||'');}
function coverLabels(t){if(t.id==='dogu-ekspresi-erzurum-kars-agri-van')return {badge:'Konaklamalı',type:'4 Gece 4 Gün'};if(isOvernight(t))return {badge:'Konaklamalı',type:t.duration||t.type};return {badge:t.badge,type:t.type};}
const monthMap={ocak:0,şubat:1,subat:1,mart:2,nisan:3,mayıs:4,mayis:4,haziran:5,temmuz:6,ağustos:7,agustos:7,eylül:8,eylul:8,ekim:9,kasım:10,kasim:10,aralık:11,aralik:11};
const weekdayMap={pazar:0,pazartesi:1,salı:2,sali:2,çarşamba:3,carsamba:3,perşembe:4,persembe:4,cuma:5,cumartesi:6};
function trToday(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const obj=Object.fromEntries(parts.map(p=>[p.type,p.value]));return new Date(Number(obj.year),Number(obj.month)-1,Number(obj.day));}
function norm(s=''){return s.toLocaleLowerCase('tr-TR').replace(/[()]/g,' ').replace(/\s+/g,' ').trim();}
function yearForMonth(month,today,explicitYear){if(explicitYear)return explicitYear;let y=today.getFullYear();if(month<today.getMonth()-3)y++;return y;}
function parseExplicitPiece(piece,today){const clean=norm(piece).replace(/ara tatil|yılbaşı özel|somestir özel|sömestir özel|ramazan dönemi|ramazan bayramı|indirimli dönem/g,'').trim();const months=Object.keys(monthMap).sort((a,b)=>b.length-a.length);const monthPattern=months.join('|');let m=clean.match(new RegExp(`(\\d{1,2})\\s*[-–]\\s*(\\d{1,2})\\s+(${monthPattern})(?:\\s+(\\d{4}))?`,'i'));if(m){const month=monthMap[norm(m[3])],year=yearForMonth(month,today,m[4]?Number(m[4]):null);return {date:new Date(year,month,Number(m[1])),label:piece.trim()};}m=clean.match(new RegExp(`(\\d{1,2})\\s+(${monthPattern})\\s*[-–]\\s*(\\d{1,2})\\s+(${monthPattern})(?:\\s+(\\d{4}))?`,'i'));if(m){const month=monthMap[norm(m[2])],year=yearForMonth(month,today,m[5]?Number(m[5]):null);return {date:new Date(year,month,Number(m[1])),label:piece.trim()};}m=clean.match(new RegExp(`(\\d{1,2})\\s+(${monthPattern})(?:\\s+(\\d{4}))?`,'i'));if(m){const month=monthMap[norm(m[2])],year=yearForMonth(month,today,m[3]?Number(m[3]):null);return {date:new Date(year,month,Number(m[1])),label:piece.trim()};}return null;}
function nextRecurringDate(text,today){const n=norm(text);if(!/boyunca her/.test(n))return null;const words=n.split(/[^a-zçğıöşü]+/i).filter(Boolean);const activeMonths=[...new Set(Object.entries(monthMap).filter(([name])=>words.includes(name)).map(([,idx])=>idx))];const weekdays=[...new Set(Object.entries(weekdayMap).filter(([name])=>words.includes(name)).map(([,idx])=>idx))];if(!activeMonths.length||!weekdays.length)return null;for(let i=0;i<370;i++){const d=new Date(today);d.setDate(today.getDate()+i);if(activeMonths.includes(d.getMonth())&&weekdays.includes(d.getDay()))return {date:d,label:new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'long',weekday:'long'}).format(d)};}return null;}
function nearestTourDate(t){const today=trToday(),recurring=nextRecurringDate(t.dates||'',today);if(recurring)return recurring;const items=String(t.dates||'').split('•').map(x=>x.trim()).filter(Boolean).map(x=>parseExplicitPiece(x,today)).filter(Boolean).filter(x=>x.date>=today).sort((a,b)=>a.date-b.date);return items[0]||null;}
window.nearestTourDate=nearestTourDate;
function tourCard(t){const labels=coverLabels(t);const typeTag=labels.type?`<span class="tour-type">${labels.type}</span>`:'';const badges=`<div class="tour-badges"><span class="tour-tag">${labels.badge}</span>${typeTag}</div>`;const media=t.detailUrl?`<a class="tour-media" href="${t.detailUrl}" aria-label="${t.title} tur detaylarını aç"><img class="tour-image" src="${t.image}" alt="${t.title} - ${t.subtitle}" loading="lazy">${badges}</a>`:`<div class="tour-media"><img class="tour-image" src="${t.image}" alt="${t.title} - ${t.subtitle}" loading="lazy">${badges}</div>`;const detailAction=t.detailUrl?`<a class="button" href="${t.detailUrl}">Tur Detayları</a>`:`<button class="button" data-tour="${t.id}">Tur Detayları</button>`;const startingPrice=t.id==='dogu-ekspresi-erzurum-kars-agri-van'?'<small>Başlayan Fiyat</small>':'';const nearest=nearestTourDate(t);const dateHtml=nearest?`<div class="tour-date"><strong>En Yakın Tarih</strong>${nearest.label}</div>`:'';return `<article class="tour-card" data-badge="${t.badge}">${media}<div class="tour-body"><div class="tour-heading"><h3>${t.title}</h3><div class="tour-price"><strong>${t.price}</strong>${startingPrice}</div></div><p class="tour-subtitle">${t.subtitle}</p><div class="tour-meta"><span>◷ ${t.duration}</span><span>⌖ ${t.departure}</span></div>${dateHtml}<div class="tour-actions">${detailAction}</div></div></article>`;}
function renderTours(filter='all'){let tours=window.TOURS||[];if(filter==='Günübirlik')tours=tours.filter(t=>!isOvernight(t));else if(filter==='Konaklamalı')tours=tours.filter(isOvernight);if(grid)grid.innerHTML=tours.map(tourCard).join('');document.querySelectorAll('[data-tour]').forEach(button=>button.addEventListener('click',()=>openTour(button.dataset.tour)));}
filterButtons.forEach(button=>button.addEventListener('click',()=>{filterButtons.forEach(b=>b.classList.remove('active'));button.classList.add('active');renderTours(button.dataset.filter);}));
function openTour(id){const t=(window.TOURS||[]).find(x=>x.id===id);if(!t)return;if(t.detailUrl){window.location.href=t.detailUrl;return;}modalImage.src=t.image;modalImage.alt=`${t.title} - ${t.subtitle}`;modalBadge.textContent=t.badge;modalTitle.textContent=`${t.title} — ${t.subtitle}`;modalPrice.textContent=t.price;modalSummary.textContent=t.summary;modalRoute.textContent=t.route;modalIncluded.textContent=t.included;modalMeta.innerHTML=`<span>${t.type||''}</span><span>◷ ${t.duration}</span><span>⌖ ${t.departure}</span><span>◉ ${t.dates}</span>`;modalWhatsapp.href=whatsappLink(t);modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}
function closeModal(){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const exactNumber=new Intl.NumberFormat('tr-TR');
const escapeHtml=(value='')=>String(value).replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
function reviewStars(rating){const count=Math.max(0,Math.min(5,Math.round(Number(rating)||0)));return `${'★'.repeat(count)}${'☆'.repeat(5-count)}`;}
function googleReviewCard(review){const author=review.author||{};const name=escapeHtml(author.name||'Google kullanıcısı');const text=escapeHtml(review.text||'');const relativeTime=escapeHtml(review.relativeTime||'');const reviewUrl=review.googleMapsUri||author.uri||'#';const photo=author.photoUri?`<img src="${escapeHtml(author.photoUri)}" alt="${name}" loading="lazy" referrerpolicy="no-referrer">`:`<span class="google-review-avatar-fallback">${name.charAt(0).toUpperCase()}</span>`;return `<article class="google-review-card"><div class="google-review-author"><div class="google-review-avatar">${photo}</div><div><strong>${name}</strong><span>${relativeTime}</span></div><span class="google-mini-g">G</span></div><div class="google-review-stars" aria-label="${Number(review.rating)||0} yıldız">${reviewStars(review.rating)}</div>${text?`<p>${text}</p>`:'<p class="google-review-no-text">Google’da yıldız değerlendirmesi bıraktı.</p>'}<a href="${escapeHtml(reviewUrl)}" target="_blank" rel="noopener">Google’da görüntüle ↗</a></article>`;}
const googleFallbackUrl='https://www.google.com/search?q=Gezi+Platformu+Mersin+yorumlar';
function showGoogleFallback(){if(googleReviewsButton)googleReviewsButton.href=googleFallbackUrl;if(googleScoreLink)googleScoreLink.href=googleFallbackUrl;if(googleRating)googleRating.textContent='Google';if(googleRatingStars)googleRatingStars.textContent='★★★★★';if(googleReviewCount)googleReviewCount.textContent='Misafir Yorumları';if(googleReviewsTrack)googleReviewsTrack.innerHTML='<div class="empty-state">Google değerlendirmelerimizi görüntülemek için butona dokunabilirsiniz.</div>';if(googleReviewsStatus){googleReviewsStatus.textContent='Google işletme profilimiz';googleReviewsStatus.className='ready';}}
async function loadGoogleReviews(){if(!googleReviewsTrack)return;try{const response=await fetch('/api/google-reviews',{cache:'no-store'});const data=await response.json();if(!response.ok||data.available===false)throw new Error(data.error||'Google yorumları kullanılamıyor');const reviews=Array.isArray(data.reviews)?data.reviews:[];const mapsUrl=data.googleMapsUri||googleFallbackUrl;googleReviewsButton.href=mapsUrl;googleScoreLink.href=mapsUrl;googleRating.textContent=data.rating?Number(data.rating).toFixed(1):'Google';googleRatingStars.textContent=reviewStars(data.rating||5);googleReviewCount.textContent=data.userRatingCount?`${exactNumber.format(data.userRatingCount)} Google yorumu`:'Google yorumları';googleReviewsTrack.innerHTML=reviews.length?reviews.map(googleReviewCard).join(''):'<div class="empty-state">Tüm değerlendirmeleri Google üzerinden inceleyebilirsiniz.</div>';googleReviewsStatus.textContent=reviews.length?`Canlı Google verileri • ${new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}`:'Google işletme profilimiz';googleReviewsStatus.className='ready';}catch{showGoogleFallback();}}
function updatePhoneTime(){if(phoneTime)phoneTime.textContent=new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'});}
renderTours();updatePhoneTime();loadGoogleReviews();setInterval(updatePhoneTime,60000);setInterval(loadGoogleReviews,1800000);
const logoAnimScript=document.createElement('script');logoAnimScript.src='logo-animation-v2.js?v=2';document.body.appendChild(logoAnimScript);
const floatingContactCss=document.createElement('link');floatingContactCss.rel='stylesheet';floatingContactCss.href='floating-contact.css?v=1';document.head.appendChild(floatingContactCss);
const floatingContactDock=document.createElement('nav');floatingContactDock.className='floating-contact-dock';floatingContactDock.setAttribute('aria-label','Hızlı iletişim');floatingContactDock.innerHTML=`<a class="floating-contact-call" href="tel:+905374978441" aria-label="0537 497 84 41 numarasını ara"><span class="floating-contact-label">Telefon Et</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.6 10.8c1.4 2.7 3.6 4.9 6.3 6.3l2.1-2.1c.3-.3.7-.4 1.1-.3 1.2.4 2.5.6 3.9.6.6 0 1 .4 1 1V20c0 .6-.4 1-1 1C10.6 21 3 13.4 3 4c0-.6.4-1 1-1h3.7c.6 0 1 .4 1 1 0 1.4.2 2.7.6 3.9.1.4 0 .8-.3 1.1l-2.4 1.8z"/></svg></a><a class="floating-contact-instagram" href="https://www.instagram.com/geziplatformuu/" target="_blank" rel="noopener" aria-label="Gezi Platformu Instagram"><span class="floating-contact-label">Instagram</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7zm10.5 1.5a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5zM12 7a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6z"/></svg></a><a class="floating-contact-map" href="https://www.google.com/maps/search/?api=1&query=Camii%C5%9Ferif+Mah.+%C4%B0stiklal+Cad.+No%3A45%2FD+Akdeniz+Mersin" target="_blank" rel="noopener" aria-label="Gezi Platformu ofisini Google Maps'te aç"><span class="floating-contact-label">Haritada Aç</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a7 7 0 0 1 7 7c0 5-7 13-7 13S5 14 5 9a7 7 0 0 1 7-7zm0 4a3 3 0 1 0 0 6 3 3 0 0 0 0-6z"/></svg></a>`;document.body.appendChild(floatingContactDock);