(()=>{
  let deferredPrompt=null;
  const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);
  const standalone=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
  const addHead=()=>{if(!document.querySelector('link[rel="manifest"]')){const l=document.createElement('link');l.rel='manifest';l.href='/manifest.webmanifest?v=1';document.head.appendChild(l)}if(!document.querySelector('meta[name="apple-mobile-web-app-capable"]')){const m=document.createElement('meta');m.name='apple-mobile-web-app-capable';m.content='yes';document.head.appendChild(m)}if(!document.querySelector('meta[name="apple-mobile-web-app-status-bar-style"]')){const m=document.createElement('meta');m.name='apple-mobile-web-app-status-bar-style';m.content='default';document.head.appendChild(m)}};
  const styles=()=>{if(document.getElementById('gp-pwa-style'))return;const s=document.createElement('style');s.id='gp-pwa-style';s.textContent=`.gp-install-modal{position:fixed;inset:0;z-index:2147483646;display:none;align-items:flex-end;justify-content:center;padding:16px;background:rgba(0,0,0,.42);backdrop-filter:blur(4px)}.gp-install-modal.open{display:flex}.gp-install-card{width:min(430px,100%);border-radius:22px;background:#fff;color:#17211f;padding:20px;box-shadow:0 24px 60px rgba(0,0,0,.28);font-family:system-ui}.gp-install-head{display:flex;gap:12px;align-items:center}.gp-install-head img{width:54px;height:54px;border-radius:14px}.gp-install-head h3{margin:0 0 4px;font-size:19px}.gp-install-head p{margin:0;color:#66716d;font-size:13px}.gp-install-actions{display:flex;gap:8px;margin-top:16px}.gp-install-actions button{flex:1;height:44px;border:0;border-radius:12px;font-weight:800;cursor:pointer}.gp-install-primary{background:#08783f;color:#fff}.gp-install-secondary{background:#eef2f0;color:#1f2926}.gp-install-help{margin:14px 0 0;color:#53605b;font-size:13px;line-height:1.5}html[data-site-theme="dark"] .gp-install-card{background:#141b19;color:#edf3f0}html[data-site-theme="dark"] .gp-install-head p,html[data-site-theme="dark"] .gp-install-help{color:#bdc8c3}html[data-site-theme="dark"] .gp-install-secondary{background:#27302d;color:#fff}`;document.head.appendChild(s)};
  const modal=()=>{let el=document.querySelector('.gp-install-modal');if(el)return el;el=document.createElement('div');el.className='gp-install-modal skiptranslate';el.innerHTML=`<div class="gp-install-card"><div class="gp-install-head"><img src="/favicon-192.png?v=20260821" alt=""><div><h3>Gezi Platformu’nu telefonuna ekle</h3><p>Turlarımıza tek dokunuşla ulaş.</p></div></div><p class="gp-install-help" id="gpInstallHelp"></p><div class="gp-install-actions"><button class="gp-install-secondary" id="gpInstallClose">Vazgeç</button><button class="gp-install-primary" id="gpInstallAction">Ana Ekrana Ekle</button></div></div>`;document.body.appendChild(el);el.addEventListener('click',e=>{if(e.target===el)el.classList.remove('open')});el.querySelector('#gpInstallClose').onclick=()=>el.classList.remove('open');return el};
  const show=async()=>{const el=modal(),help=el.querySelector('#gpInstallHelp'),action=el.querySelector('#gpInstallAction');if(standalone){help.textContent='Gezi Platformu zaten telefonunda uygulama gibi açık.';action.textContent='Tamam';action.onclick=()=>el.classList.remove('open');}else if(deferredPrompt){help.textContent='Uygulama simgesi ana ekranına eklenecek. Dokunduğunda doğrudan Gezi Platformu açılacak.';action.textContent='Ana Ekrana Ekle';action.onclick=async()=>{deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;el.classList.remove('open')}}else if(isiOS){help.textContent='iPhone’da Safari’nin altındaki Paylaş simgesine dokun, ardından “Ana Ekrana Ekle” seçeneğini seç.';action.textContent='Anladım';action.onclick=()=>el.classList.remove('open');}else{help.textContent='Tarayıcının menüsünden “Ana ekrana ekle” veya “Uygulamayı yükle” seçeneğini kullanabilirsin.';action.textContent='Anladım';action.onclick=()=>el.classList.remove('open');}el.classList.add('open')};
  const addButton=()=>{const controls=document.querySelector('.gp-site-controls');if(!controls||document.getElementById('gpInstallToggle'))return false;const b=document.createElement('button');b.id='gpInstallToggle';b.className='gp-site-control';b.type='button';b.title='Telefonuna ekle';b.setAttribute('aria-label','Gezi Platformu’nu telefonuna ekle');b.textContent='📲';b.onclick=show;controls.appendChild(b);return true};
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;addButton()});
  window.addEventListener('appinstalled',()=>{deferredPrompt=null;const b=document.getElementById('gpInstallToggle');if(b)b.textContent='✓'});
  const mount=()=>{addHead();styles();if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js?v=1').catch(()=>{});if(!addButton()){let n=0;const t=setInterval(()=>{if(addButton()||++n>30)clearInterval(t)},200)}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
