(()=>{
const P={
'/dogu-ekspresi.html':['Mersin Adana Niğde Çıkışlı Doğu Ekspresi Turu 2026 | Gezi Platformu','Mersin, Tarsus, Adana ve Niğde çıkışlı Doğu Ekspresi Kars Erzurum Ağrı Van turu. Güncel tarihler, fiyatlar, oteller, rota ve rezervasyon bilgileri.','Doğu Ekspresi Kars Erzurum Ağrı Van Turu','Kış ve kültür turu',['Mersin','Tarsus','Adana','Niğde']],
'/buyuk-bati-karadeniz.html':['Mersin Adana Niğde Çıkışlı Batı Karadeniz Turu 2026 | Gezi Platformu','Mersin, Adana ve Niğde çıkışlı Büyük Batı Karadeniz turu. Yedigöller, Abant, Safranbolu, Amasra, Horma, Ilıca ve Sinop rotası.','Büyük Batı Karadeniz Turu','Doğa ve kültür turu',['Mersin','Adana','Niğde']],
'/sonbahar-ozel-bati-karadeniz.html':['Mersin Adana Niğde Çıkışlı Sonbahar Batı Karadeniz Turu | Gezi Platformu','Mersin, Adana ve Niğde çıkışlı Sonbahar Özel Batı Karadeniz turu. Yedigöller, Gölcük, Safranbolu, Amasra, Horma ve Ilıca.','Sonbahar Özel Batı Karadeniz Turu','Sonbahar doğa ve kültür turu',['Mersin','Adana','Niğde']],
'/kadim-topraklar-turu.html':['Mersin Adana Niğde Çıkışlı Mardin Midyat Nemrut Turu | Gezi Platformu','Mersin, Adana ve Niğde çıkışlı Kadim Topraklar turu. Adıyaman, Nemrut, Diyarbakır, Midyat ve Mardin programı, tarih ve fiyatlar.','Kadim Topraklar Mardin Midyat Nemrut Turu','Kültür turu',['Mersin','Adana','Niğde']],
'/sivas-divrigi-turu.html':['Mersin Adana Niğde Çıkışlı Sivas Divriği Turu | Gezi Platformu','Mersin, Adana ve Niğde çıkışlı Sivas Divriği günübirlik turu. Divriği Ulu Camii, Darüşşifa, Sivas Kongre Merkezi ve Şifaiye Medresesi.','Sivas ve Divriği Günübirlik Turu','Kültür turu',['Mersin','Adana','Niğde']],
'/hatay-turu.html':['Mersin Adana Çıkışlı Hatay Turu | Günübirlik | Gezi Platformu','Mersin ve Adana çıkışlı Hatay günübirlik turu. Titus Tüneli, Beşikli Mağarası, Habib-i Neccar Camii, Harbiye Şelaleleri ve Uzun Çarşı.','Hatay Günübirlik Turu','Kültür turu',['Mersin','Adana']],
'/mardin-midyat-turu.html':['Mersin Adana Osmaniye Çıkışlı Mardin Midyat Turu | Gezi Platformu','Mersin, Adana ve Osmaniye çıkışlı günübirlik Mardin Midyat turu. Kasımiye Medresesi, Mor Gabriel, Midyat ve Mardin tarihi sokakları.','Mardin ve Midyat Günübirlik Turu','Kültür turu',['Mersin','Adana','Osmaniye']],
'/camliyayla-doga-turu.html':['Mersin Çıkışlı Çamlıyayla Doğa Turu | Günübirlik | Gezi Platformu','Mersin çıkışlı Çamlıyayla günübirlik doğa turu. Güncel rota, tur tarihi, fiyat, kalkış noktaları ve rezervasyon bilgileri.','Çamlıyayla Günübirlik Doğa Turu','Doğa turu',['Mersin']],
'/aladaglar-doga-turu.html':['Mersin Adana Çıkışlı Aladağlar Doğa Turu | Günübirlik | Gezi Platformu','Mersin ve Adana çıkışlı Aladağlar günübirlik doğa turu. Güncel rota, tarih, fiyat, kalkış noktaları ve rezervasyon bilgileri.','Aladağlar Günübirlik Doğa Turu','Doğa turu',['Mersin','Adana']],
'/osmaniye-doga-turu.html':['Mersin Adana Çıkışlı Osmaniye Doğa Turu | Günübirlik | Gezi Platformu','Mersin ve Adana çıkışlı Osmaniye günübirlik doğa turu. Güncel rota, tarih, fiyat, kalkış noktaları ve rezervasyon bilgileri.','Osmaniye Günübirlik Doğa Turu','Doğa turu',['Mersin','Adana']],
'/baskonus-menzelet-ali-kayasi.html':['Mersin Adana Çıkışlı Başkonuş Menzelet Ali Kayası Turu | Gezi Platformu','Mersin ve Adana çıkışlı Başkonuş Yaylası, Menzelet Gölü, Ali Kayası Cam Teras ve Kahramanmaraş rotalı günübirlik doğa turu.','Başkonuş Menzelet ve Ali Kayası Turu','Doğa turu',['Mersin','Adana']],
'/kayseri-doga-turu.html':['Mersin Adana Niğde Çıkışlı Kayseri Doğa Turu | Gezi Platformu','Mersin, Adana ve Niğde çıkışlı Kayseri günübirlik doğa turu. Güncel rota, tarih, fiyat, kalkış noktaları ve rezervasyon bilgileri.','Kayseri Günübirlik Doğa Turu','Doğa turu',['Mersin','Adana','Niğde']]
};
const c=P[location.pathname];if(!c)return;const [title,desc,h1,type,deps]=c,canon='https://www.geziplatformuu.com'+location.pathname;
const meta=(q,a,v)=>{let e=document.querySelector(q);if(!e){e=document.createElement('meta');document.head.appendChild(e)}Object.entries(a).forEach(([k,x])=>e.setAttribute(k,x));e.content=v};
document.title=title;meta('meta[name="description"]',{name:'description'},desc);meta('meta[property="og:title"]',{property:'og:title'},title);meta('meta[property="og:description"]',{property:'og:description'},desc);meta('meta[property="og:url"]',{property:'og:url'},canon);meta('meta[name="twitter:title"]',{name:'twitter:title'},title);meta('meta[name="twitter:description"]',{name:'twitter:description'},desc);
const heading=document.querySelector('h1');if(heading)heading.textContent=h1;let link=document.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=canon;
const image=document.querySelector('meta[property="og:image"]')?.content||document.querySelector('main img')?.src||'https://www.geziplatformuu.com/favicon-192.png';
document.getElementById('gp-tour-seo-schema')?.remove();const graph={"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":canon+'#webpage',url:canon,name:title,description:desc,inLanguage:'tr-TR',isPartOf:{"@id":"https://www.geziplatformuu.com/#website"},about:{"@id":canon+'#tour'}},{"@type":"BreadcrumbList","@id":canon+'#breadcrumb',itemListElement:[{"@type":"ListItem",position:1,name:'Ana Sayfa',item:'https://www.geziplatformuu.com/'},{"@type":"ListItem",position:2,name:h1,item:canon}]},{"@type":"TouristTrip","@id":canon+'#tour',name:h1,description:desc,url:canon,image,touristType:type,provider:{"@type":"TravelAgency","@id":"https://www.geziplatformuu.com/#business",name:'Gezi Platformu',legalName:'Özbek Turizm',url:'https://www.geziplatformuu.com/',telephone:'+90 537 497 84 41',identifier:'TÜRSAB A-8660'},itinerary:deps.map(x=>({"@type":"Place",name:x+' kalkış noktası'}))}]};const s=document.createElement('script');s.type='application/ld+json';s.id='gp-tour-seo-schema';s.textContent=JSON.stringify(graph);document.head.appendChild(s);
if(!document.querySelector('.gp-seo-links')){const city={Mersin:'/mersin-cikisli-turlar.html',Adana:'/adana-cikisli-turlar.html','Niğde':'/nigde-cikisli-turlar.html'};const links=deps.filter(x=>city[x]).map(x=>`<a href="${city[x]}">${x} çıkışlı turlar</a>`).join('');const box=document.createElement('section');box.className='gp-seo-links';box.setAttribute('aria-label','İlgili tur bağlantıları');box.innerHTML=`<strong>Bu tura nereden katılabilirsiniz?</strong><p>${deps.join(' • ')} kalkışlı tur seçeneklerini inceleyebilirsiniz.</p><div>${links}<a href="/">Tüm güncel turlar</a></div>`;const target=document.querySelector('.reserve-box,.contact-box')||document.querySelector('main');target?.insertAdjacentElement('beforebegin',box);const st=document.createElement('style');st.textContent='.gp-seo-links{width:min(940px,calc(100% - 28px));margin:18px auto 28px;padding:18px;border:1px solid #e5e9e7;border-radius:16px;background:#fff}.gp-seo-links strong{display:block;margin-bottom:5px}.gp-seo-links p{margin:0 0 10px;font-size:13px}.gp-seo-links div{display:flex;flex-wrap:wrap;gap:8px}.gp-seo-links a{padding:9px 11px;border-radius:999px;background:#f2f5f4;font-size:12px;font-weight:800;color:#17211d;text-decoration:none}html[data-site-theme="dark"] .gp-seo-links{background:#141b19!important;border-color:#28332f!important;color:#edf3f0!important}html[data-site-theme="dark"] .gp-seo-links a{background:#222b28;color:#edf3f0}';document.head.appendChild(st)}
})();